# Generated by Django 3.0.2 on 2020-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sec_writer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
