# Generated by Django 3.0.2 on 2020-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prev_price',
            field=models.IntegerField(default=0),
        ),
    ]
